### ISSUE TITLE
backend crash in local install of dockerized version on macosx

### ISSUE THREAD

**Issue by anoopsarkar** [sfu-natlang/lensingwikipedia#197]
Once it happens, it happens repeatedly. Leaves the site non-functional. Even after restarting it seems that port 8080 is not open to requests: `nc -z 192.168.99.100 8080` indicates that 8080 is closed.

```
query_1 | DEBUG:root:request at 2015-08-25 21:58:07.855424
query_1 | handling constraint "4" of type "fieldvalue"
query_1 | handling view "0" of type "descriptions": generating view
query_1 | handling view "10" of type "countbyfieldvalue": generating view
query_1 | whoosh pre-paginated search results: <Top 25 Results for And([Term(u'person', u'Martin Luther')]) runtime=0.0194218158722>
query_1 | generating field counts for fields: person
query_1 | whoosh search results: <Top 43 Results for And([Term(u'person', u'Martin Luther')]) runtime=0.0154829025269>
query_1 | 192.168.99.1 - - [25/Aug/2015 21:58:08] "POST / HTTP/1.1" 200 23128
query_1 | Traceback (most recent call last):
query_1 |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 86, in run
query_1 |     self.finish_response()
query_1 |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
query_1 |     self.write(data)
query_1 |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 212, in write
query_1 |     self.send_headers()
query_1 |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 270, in send_headers
query_1 |     self.send_preamble()
query_1 |   File "/usr/lib/python2.7/wsgiref/handlers.py", line 194, in send_preamble
query_1 |     'Date: %s\r\n' % format_date_time(time.time())
query_1 |   File "/usr/lib/python2.7/socket.py", line 324, in write
query_1 |     self.flush()
query_1 |   File "/usr/lib/python2.7/socket.py", line 303, in flush
query_1 |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
query_1 | error: [Errno 32] Broken pipe
query_1 | 192.168.99.1 - - [25/Aug/2015 21:58:08] "POST / HTTP/1.1" 500 59
query_1 | Traceback (most recent call last):
query_1 |   File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
query_1 |     self.process_request(request, client_address)
query_1 |   File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
query_1 |     self.finish_request(request, client_address)
query_1 |   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
query_1 |     self.RequestHandlerClass(request, client_address, self)
query_1 |   File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
query_1 |     self.finish()
query_1 |   File "/usr/lib/python2.7/SocketServer.py", line 710, in finish
query_1 |     self.wfile.close()
query_1 |   File "/usr/lib/python2.7/socket.py", line 279, in close
query_1 |     self.flush()
query_1 |   File "/usr/lib/python2.7/socket.py", line 303, in flush
query_1 |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
query_1 | error: [Errno 32] Broken pipe
```

**Comment by vlad003** [comment]
If you remove all containers and run `docker-compose up` again, does it keep crashing repeatedly?

**Comment by anoopsarkar** [comment]
removing the containers worked. I updated the troubleshooting section of website.md. Closing this issue.
